### ISSUE TITLE
atom-ide-ui launch checklist

### ISSUE THREAD

**Issue by hansonw** [atom/atom-languageclient#44]
The necessary UI components to support `atom-languageclient` are being developed over in https://github.com/facebook/nuclide/tree/master/modules/atom-ide-ui (or rather, they're being moved in from Nuclide piece-by-piece), which will soon be published as a standalone package.

This checklist tracks the progress of that effort.

# Beta launch blockers

- [x] Make the Nuclide unified package loader reusable for atom-ide-ui (@wbinnssmith)
- [x] Move all packages into `atom-ide-ui`
    - [x] hyperclick
    - [x] diagnostics / diagnostics-ui
    - [x] busy-signal
    - [x] code-format
    - [x] code-highlight
    - [x] datatip
    - [x] definitions
    - [x] ~~definition-service~~ (just dropping this)
      - [x] Drop unused getDefinitionById API
    - [x] find-references
    - [x] outline-view
    - [x] hyperclick-definition-preview
- [x] Strip atom-ide-ui packages of their Nuclide branding.
    - [x] Gracefully migrate commands/keybindings
    - [x] Gracefully migrate CSS styles (Not sure if necessary? depends on open-source themes) 

# Public launch blockers

- [x] Documentation
    - [x] All public APIs and features should be well-documented.
- [x] Figure out a consistent apm publishing mechanism
    - [x] Set up Lerna to enable easy publishing of atom-ide-ui and its dependencies
- [x] Move repository to "facebook-atom/atom-ide-ui" and sync code from Nuclide.

**Comment by hansonw** [comment]
I've published an initial package to https://atom.io/packages/atom-ide-ui. I still need to clean up the keymaps, commands, menus, and styles before we publicize it further though :)

**Comment by hansonw** [comment]
Docs are still a WIP over at https://github.com/facebook-atom/atom-ide-ui/tree/master/docs but I'm going to mark this as done. 🎉🎉
